apiVersion: v1
kind: PersistentVolume
metadata:
  name: oauth-mongodb
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oauth-mongodb
  namespace: social-science
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth-mongodb
  labels:
    app: oauth-mongodb
    type: database
  namespace: social-science
spec:
  selector:
    matchLabels:
      app: oauth-mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: oauth-mongodb
        type: database
    spec:
      imagePullSecrets:
        - name: docker-hub
      containers:
        - name: oauth-mongodb
          image: mongo
          ports:
            - name: oauth-mongodb
              containerPort: 27017
          volumeMounts:
            - name: oauth-mongodb-storage
              mountPath: /data/db
      volumes:
        - name: oauth-mongodb-storage
          persistentVolumeClaim:
            claimName: oauth-mongodb