apiVersion: v1
kind: Service
metadata:
  labels:
    name: oauth-mongodb
    type: database
  name: oauth-mongodb
  namespace: social-science
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: oauth-mongodb