security:
  oauth2:
    authorization:
      check-token-access: fullyAuthenticated
    client:
      access-token-validity-seconds: 300 # five minutes
      refresh-token-validity-seconds: 600 # ten minutes
      authorized-grant-types: password,refresh_token
      client-id: datasciencenet
      client-secret: 1234
      scope: read,write

spring:
  security:
    user:
      name: user
      password: 1234
  application:
    name: oauth-social-science
  data:
    mongodb:
      port: 27017
      host: oauth-mongodb.social-science
      database: auth

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org:
      springframework:
        security: DEBUG
        data: DEBUG